-- SQL comum a H2 (modo PostgreSQL) e PostgreSQL.

create table templates (
    id bigint generated by default as identity primary key,
    codigo varchar(10) not null,
    versao integer not null,
    categoria varchar(255) not null,
    check (categoria in ('HOBBY','CURSO')),
    titulo varchar(200) not null,
    pergunta_decisao varchar(1000) not null,
    duracao_dias integer not null,
    sessoes_sugeridas integer not null,
    minutos_por_sessao_sugerido integer not null,
    descricao varchar(10000) not null,
    unique (codigo, versao),
    check (versao > 0),
    check (categoria in ('HOBBY','CURSO')),
    check (duracao_dias = 7),
    check (sessoes_sugeridas > 0),
    check (minutos_por_sessao_sugerido > 0)
);

create table decisoes (
    id bigint generated by default as identity primary key,
    titulo varchar(200) not null,
    categoria varchar(255) not null,
    check (categoria in ('HOBBY','CURSO')),
    motivacao varchar(4000) not null,
    experiencia_anterior varchar(255) not null,
    check (experiencia_anterior in ('NENHUMA','OCASIONAL','REGULAR')),
    participante_codigo varchar(64) not null,
    check (categoria in ('HOBBY','CURSO')),
    check (experiencia_anterior in ('NENHUMA','OCASIONAL','REGULAR'))
);

create table experimentos (
    id bigint generated by default as identity primary key,
    decisao_id bigint not null references decisoes(id),
    template_codigo varchar(10) not null,
    template_versao integer not null,
    template_categoria varchar(255) not null,
    check (template_categoria in ('HOBBY','CURSO')),
    template_titulo varchar(200) not null,
    template_pergunta_decisao varchar(1000) not null,
    template_duracao_dias integer not null,
    template_sessoes_sugeridas integer not null,
    template_minutos_por_sessao_sugerido integer not null,
    template_descricao varchar(10000) not null,
    descricao_final_editada varchar(10000) not null,
    material_provedor_formato varchar(2000),
    data_inicio date not null,
    data_fim_prevista date not null,
    situacao varchar(255) not null,
    check (situacao in ('PLANEJADO','EM_ANDAMENTO','CONCLUIDO','INTERROMPIDO','NAO_INICIADO')),
    versao_registro bigint not null default 0,
    check (template_duracao_dias = 7),
    check (template_categoria in ('HOBBY','CURSO')),
    check (situacao in ('PLANEJADO','EM_ANDAMENTO','CONCLUIDO','INTERROMPIDO','NAO_INICIADO')),
    check (data_fim_prevista >= data_inicio)
);

create table pre_testes (
    id bigint generated by default as identity primary key,
    experimento_id bigint not null unique references experimentos(id),
    sessoes_esperadas integer not null,
    tempo_esperado_minutos integer not null,
    gasto_esperado numeric(12,2) not null,
    dificuldade_esperada integer not null,
    satisfacao_esperada integer not null,
    obstaculo_principal_esperado varchar(255) not null,
    check (obstaculo_principal_esperado in ('O0','O1','O2','O3','O4','O5','O6','O7','O8','O9')),
    descricao_outro varchar(2000),
    como_obstaculo_apareceria varchar(4000),
    seguranca_decidir_antes integer not null,
    intencao_antes varchar(255) not null,
    check (intencao_antes in ('CONTINUAR','ADAPTAR','TESTAR_DE_NOVO','ADIAR','NAO_SEI')),
    data_hora_resposta timestamp(6) with time zone not null,
    descricao_plano_na_resposta varchar(10000) not null,
    material_na_resposta varchar(2000),
    data_inicio_na_resposta date not null,
    data_fim_na_resposta date not null,
    check (sessoes_esperadas >= 0),
    check (tempo_esperado_minutos >= 0),
    check (gasto_esperado >= 0),
    check (dificuldade_esperada between 1 and 5),
    check (satisfacao_esperada between 1 and 5),
    check (seguranca_decidir_antes between 0 and 10),
    check (obstaculo_principal_esperado <> 'O9' or (descricao_outro is not null and length(trim(descricao_outro)) > 0))
);

create table pos_testes (
    id bigint generated by default as identity primary key,
    experimento_id bigint not null unique references experimentos(id),
    situacao_experimento varchar(255) not null,
    check (situacao_experimento in ('A','B','C','D')),
    motivo_se_interrompeu_ou_nao_iniciou varchar(4000),
    data_interrupcao date,
    sessoes_realizadas integer not null,
    tempo_realizado_minutos integer not null,
    custo_realizado numeric(12,2) not null,
    dificuldade_percebida varchar(255) not null,
    check (dificuldade_percebida in ('NIVEL_1','NIVEL_2','NIVEL_3','NIVEL_4','NIVEL_5','NAO_SE_APLICA')),
    satisfacao_percebida varchar(255) not null,
    check (satisfacao_percebida in ('NIVEL_1','NIVEL_2','NIVEL_3','NIVEL_4','NIVEL_5','NAO_SE_APLICA')),
    obstaculo_encontrado varchar(255) not null,
    check (obstaculo_encontrado in ('O0','O1','O2','O3','O4','O5','O6','O7','O8','O9')),
    descricao_outro varchar(2000),
    relato_exemplo varchar(4000),
    seguranca_decidir_depois integer not null,
    proximo_passo varchar(255) not null,
    check (proximo_passo in ('CONTINUAR','ADAPTAR','TESTAR_DE_NOVO','ADIAR','NAO_SEI')),
    o_que_pesou_na_escolha varchar(4000),
    contribuicao_percebida_app varchar(4000),
    contexto_mudancas varchar(4000),
    data_hora_resposta timestamp(6) with time zone not null,
    check (situacao_experimento in ('A','B','C','D')),
    check (sessoes_realizadas >= 0),
    check (tempo_realizado_minutos >= 0),
    check (custo_realizado >= 0),
    check (seguranca_decidir_depois between 0 and 10),
    check (situacao_experimento not in ('C','D') or (motivo_se_interrompeu_ou_nao_iniciou is not null and length(trim(motivo_se_interrompeu_ou_nao_iniciou)) > 0)),
    check ((situacao_experimento = 'D' and sessoes_realizadas = 0 and dificuldade_percebida = 'NAO_SE_APLICA' and satisfacao_percebida = 'NAO_SE_APLICA') or (situacao_experimento <> 'D' and sessoes_realizadas > 0 and dificuldade_percebida <> 'NAO_SE_APLICA' and satisfacao_percebida <> 'NAO_SE_APLICA')),
    check (data_interrupcao is null or situacao_experimento = 'C'),
    check (obstaculo_encontrado <> 'O9' or (descricao_outro is not null and length(trim(descricao_outro)) > 0))
);

create table registros_sessao (
    id bigint generated by default as identity primary key,
    experimento_id bigint not null references experimentos(id),
    data date not null,
    minutos_dedicados integer not null,
    gasto_adicional numeric(12,2) not null,
    nota_opcional varchar(4000),
    check (minutos_dedicados >= 0),
    check (gasto_adicional >= 0)
);

create table comparacoes (
    id bigint generated by default as identity primary key,
    experimento_id bigint not null unique references experimentos(id),
    diferenca_sessoes integer not null,
    diferenca_tempo_minutos integer not null,
    diferenca_gasto numeric(12,2) not null,
    transicao_dificuldade varchar(255) not null,
    check (transicao_dificuldade in ('PIOROU','MANTEVE','MELHOROU','NAO_SE_APLICA')),
    transicao_satisfacao varchar(255) not null,
    check (transicao_satisfacao in ('PIOROU','MANTEVE','MELHOROU','NAO_SE_APLICA')),
    obstaculo_mudou boolean not null,
    intencao_antes varchar(255) not null,
    check (intencao_antes in ('CONTINUAR','ADAPTAR','TESTAR_DE_NOVO','ADIAR','NAO_SEI')),
    intencao_depois varchar(255) not null,
    check (intencao_depois in ('CONTINUAR','ADAPTAR','TESTAR_DE_NOVO','ADIAR','NAO_SEI')),
    mudanca_seguranca integer not null,
    foreign key (experimento_id) references pre_testes(experimento_id),
    foreign key (experimento_id) references pos_testes(experimento_id),
    check (mudanca_seguranca between -10 and 10)
);

create index idx_experimentos_decisao on experimentos(decisao_id);
create index idx_registros_experimento_data on registros_sessao(experimento_id, data);
