spring:
  application:
    name: antes-api
  profiles:
    default: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-numbers-for-enums: true
      accept-float-as-int: false
server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${PORT:8080}
antes:
  fuso-horario: America/Sao_Paulo
